# Sample .travis.yml for R projects.
# Taken from my fork of Craig Citro's r-travis
#
# See https://github.com/eddelbuettel/r-travis/
# and https://github.com/craigcitro/r-travis
#
# See README.md for instructions.

language: c
script: ./travis-tool.sh run_tests
before_script:
  - curl -OL http://raw.github.com/eddelbuettel/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap
  - ./travis-tool.sh install_aptget libhiredis-dev 
  - ./travis-tool.sh install_r Rcpp

